"""change url validate

Revision ID: 80428ac80fc1
Revises: e8cb98fdf514
Create Date: 2023-11-16 17:48:41.453698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80428ac80fc1'
down_revision = 'e8cb98fdf514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('url', sa.String(), nullable=True))
    op.drop_column('files', 'imageUrl')
    op.add_column('steps', sa.Column('url', sa.String(), nullable=True))
    op.drop_column('steps', 'imageUrl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('imageUrl', sa.VARCHAR(), nullable=False))
    op.drop_column('steps', 'url')
    op.add_column('files', sa.Column('imageUrl', sa.VARCHAR(), nullable=False))
    op.drop_column('files', 'url')
    # ### end Alembic commands ###
