"""add order field to step

Revision ID: e7fcb8593c64
Revises: f47596b9a0a3
Create Date: 2023-12-22 21:33:44.013775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7fcb8593c64'
down_revision = 'f47596b9a0a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'order')
    # ### end Alembic commands ###
