"""add unique constraint to app name

Revision ID: 783c20684007
Revises: 4a63dee2114c
Create Date: 2023-11-24 10:02:32.275153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783c20684007'
down_revision = '4a63dee2114c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'applications', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='unique')
    # ### end Alembic commands ###
