"""add innerHTML field to Steps

Revision ID: f47596b9a0a3
Revises: 783c20684007
Create Date: 2023-12-01 21:23:37.787455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47596b9a0a3'
down_revision = '783c20684007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('innerHTML', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'innerHTML')
    # ### end Alembic commands ###
