"""add type column

Revision ID: 4a63dee2114c
Revises: 80428ac80fc1
Create Date: 2023-11-22 16:00:29.054550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a63dee2114c'
down_revision = '80428ac80fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('type', sa.String(length=50), nullable=False, server_default='button'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'type')
    # ### end Alembic commands ###
