"""add mockApi table

Revision ID: bb305bdf5421
Revises: e7fcb8593c64
Create Date: 2024-02-29 00:13:33.634132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb305bdf5421'
down_revision = 'e7fcb8593c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mockApis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicationId', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=60), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('responseType', sa.String(), nullable=False),
    sa.Column('responseBody', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['applicationId'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mockApis')
    # ### end Alembic commands ###
