"""add audio attr in step

Revision ID: b7ba6a9acc2a
Revises: bb305bdf5421
Create Date: 2024-03-02 11:13:07.986863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ba6a9acc2a'
down_revision = 'bb305bdf5421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('audioFileName', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'audioFileName')
    # ### end Alembic commands ###
