"""delete url attr in step

Revision ID: 804ee8ae4788
Revises: b7ba6a9acc2a
Create Date: 2024-03-02 11:55:58.863895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804ee8ae4788'
down_revision = 'b7ba6a9acc2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('url', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
